### ISSUE TITLE
Try `Dagger` on multinode

### ISSUE THREAD

**Issue by jofrevalles** [bsc-quantic/Tenet.jl#100]
### Summary
Try the integration of our `Tensor` methods with `Dagger` on a multinode execution. See issue #95 for more information.

**Comment by mofeing** [comment]
I'm interested on how the network affects the execution, so I would like a recreation of #95 but with 1 core/worker and 1 worker/node. It would be nice to try it in CTE-AMD and Marenostrum 4.
