### ISSUE TITLE
Specialize `contract` method for `Dagger.DArray` tensors

### ISSUE THREAD

**Issue by Todorbsc** [bsc-quantic/Tenet.jl#123]
When the tensors to be contracted are matrices, the generated tasks are executed in parallel, and the total number of tasks makes sense (first image). The problem arises when the tensors to be contracted are of higher order, as EinCode starts to perform permutations in the dimensions and reshapes to carry out the contraction, seemingly generating an endless number of tasks (second image, and it hasn't even reached the end of the contraction). In the case where the tensors were matrices, these operations are not necessary, and the contraction operation is merely the matrix product, yielding the expected result.

![two_matrices_contraction_darrays](https://github.com/bsc-quantic/Tenet.jl/assets/145352308/ea8eba27-2981-47f5-b661-0064b876d0e2)

![3-order_tensor_contraction_darrays](https://github.com/bsc-quantic/Tenet.jl/assets/145352308/5af13a76-78f1-4078-aaa3-ad60ef6eed75)

**Comment by jofrevalles** [comment]
Very interesting! This may due to what I found a while ago, `Dagger` does not currently support `permutedims`! https://github.com/JuliaParallel/Dagger.jl/issues/395
