### ISSUE TITLE
Add helper functions to extract physical and virtual indices of an Ansatz

### ISSUE THREAD

**Issue by starsfordummies** [bsc-quantic/Tenet.jl#182]
so far I'm using for a chain
```
siteinds(psi::Chain) =  inds(psi, set=:open)
linkinds(psi::Chain) =  inds(psi, set=:inner)
```
not sure how that deals with ordering etc..

**Comment by starsfordummies** [comment]
So maybe something like 
```
linkind(psi::Chain, i::Int) = inds(psi, bond=[Site(i),Site(i+1)])
linkinds(psi::Chain) = [linkind(psi, ii) for ii in eachindex(sites(psi))[1:end-1]]
```
or something that works directly with `Site`s but I don't know if I have `s1 = Site(1)` how to get `Site(2)` from it

**Comment by starsfordummies** [comment]
so the second example I cooked would work for you, right ? 
agree for the `bonds`  function!

**Comment by mofeing** [comment]
> so the second example I cooked would work for you, right ? agree for the `bonds` function!

yeah, but I'm gonna write a implementation with some internals that will do things faster and with less allocs
