### ISSUE TITLE
Implement LU factorization for `Tensor`

### ISSUE THREAD

**Issue by mofeing** [bsc-quantic/Tenet.jl#26]

**Comment by mofeing** [comment]
Moved to [bsc-quantic/Tensors.jl](https://github.com/bsc-quantic/Tensors.jl).

**Comment by jofrevalles** [comment]
The `LU` decomposition was proposed in a [PR](https://github.com/bsc-quantic/Tensors.jl/pull/26) in `Tensors.jl`. I have 
 now made the PR #94 here on `Tenet` with the same proposed code.
