### ISSUE TITLE
ReactantExt: Einsum -> DotGeneral

### ISSUE THREAD

**Issue by wsmoses** [bsc-quantic/Tenet.jl#265]
https://github.com/bsc-quantic/Tenet.jl/blob/2bba50cb8102327cde8289c05bc986783a05bb8a/ext/TenetReactantExt.jl#L170

So:

```
einsum

This operation is on its way out of StableHLO, so it is not included in the StableHLO specification: https://github.com/openxla/stablehlo/issues/3.

Informally, this operation does the same thing as TF's einsum: https://www.tensorflow.org/api_docs/python/tf/einsum
```

Presumably this can be rewritten as dot general and the likes?

**Comment by mofeing** [comment]
The corresponding changes are being developed in bsc-quantic/Tenet.jl#268

The only standing issue is the replacement for `unary_einsum`, which is not super critical but quite convenient. I guess I will need `stablehlo.reduce` but we don't have the Ops yet and using `stablehlo.dynamic_update_slice` for retrieving the diagonal will be terrible for codegen.
