### ISSUE TITLE
Canonical form for `MatrixProductState` and `MatrixProductOperator`

### ISSUE THREAD

**Issue by jofrevalles** [bsc-quantic/Tenet.jl#45]
### Summary 
Add a canonical form transformation for a given `MatrixProductState`. This will be useful for different algorithms.

**Comment by mofeing** [comment]
There is only **canonical form**. Whether it is right- or left-canonical it's just the direction of the isometries (and the location of the weights) so for me there is only 1 canonical transformation, with some parameter to choose the orthogonality center (could be one site or a range of sites).

**Comment by jofrevalles** [comment]
Okay, makes sense. I will update the issue description. Nevertheless, we should store the orthogonality center somewhere.

**Comment by mofeing** [comment]
> We could also think about adding a way to check the canonical form of a Tensor in a MatrixProductState. Should we store this in meta?

This could be nice to avoid extra computation but I'm not sure we could always rely on it. First let's implement the canonical transformation, then a function that computes the orthogonality center and we'll figure out how to do this last part as we see the design evolves.

For functions that could benefit from caching the orthogonality center, we could let the user pass it as an argument, just like quimb does.

**Comment by mofeing** [comment]
Code moved to [`Qrochet.jl`](https://github.com/bsc-quantic/Qrochet.jl).
