### ISSUE TITLE
Consider accepting three-dimensional edge `Tensor`s for `MatrixProductState`

### ISSUE THREAD

**Issue by jofrevalles** [bsc-quantic/Tenet.jl#47]
We could loose the current requirements that disallow creating a `MatrixProductState` where all the tensors are three-dimensional. In that case, we could just check that the dimension of the left and right index for the first and last `Tensor`, respectively, are one.

I think this could allow an easier implementation of the algorithms where `MatrixProductState` are used since it is easier to generalize the code, and we wouldn't have to worry about the boundary `Tensor`s being different. 
What do you think?

**Comment by mofeing** [comment]
Related code moved to [`Qrochet.jl`](https://github.com/bsc-quantic/Qrochet.jl).
