### ISSUE TITLE
Enhance `replace!(tn::TensorNetwork, ...)` function for more flexible `Tensor` replacements

### ISSUE THREAD

**Issue by jofrevalles** [bsc-quantic/Tenet.jl#56]
### Summary
Currently, the `replace!` function can replace a `Tensor` within a `TensorNetwork` but only under the condition that the new `Tensor` has the same `labels` as the original one. This restriction imposes a considerable limitation on our usage of this function, especially in scenarios where we might want to replace a tensor with another one that differs in size and consequently, in labels.

At the moment, this implementation could potentially introduce problems. Specifically, the `TensorNetwork` has an `inds` field that  links indexes with tensors. In its current form, we cannot add a new index to a `TensorNetwork` because of the immutable nature of this struct.

The recent refactor presented in PR #55 removes the `inds` field, allowing a more generalized replacement of tensors like the one just explained.

**Comment by jofrevalles** [comment]
Marked with the "on hold" label, since we are waiting for the new refactor to be merged

**Comment by mofeing** [comment]
#55 included a new `replace!` method that can replace a `Tensor` with a `TensorNetwork` as long as the open indices of the `TensorNetwork` match the labels of the `Tensor`.

**Comment by jofrevalles** [comment]
We could now enhance the `replace!` function so it enables the replacement of tensors that have different labels. However, we should discuss how we want that and what happens to the other tensors connected to the replaced tensor.

**Comment by mofeing** [comment]
> Update: this can be already implemented

But we haven't discussed the semantics yet... I have concerns on adding new labels not in the Tensor Network (or renaming) or resizing an index from a `Tensor`.

If you suggest some coherent semantics, I will consider them.

**Comment by mofeing** [comment]
@jofrevalles I think we can close this since we now have `@unsafe_region` right?

**Comment by jofrevalles** [comment]
Yes!
