### ISSUE TITLE
Implement `norm(MatrixProductOperator)` and `norm(other TN models)`

### ISSUE THREAD

**Issue by emapuljak** [bsc-quantic/Tenet.jl#64]
`norm(MPO)` and `norm(Composite TN)` not implemented for now. 
`norm(MPS)` is implemented.

**Comment by jofrevalles** [comment]
The `norm` of any `TensorNetwork{<:Quantum}` state is already implemented in our [code](https://github.com/bsc-quantic/Tenet.jl/blob/master/src/Quantum/Quantum.jl#L178), but you are right that there were problems for the `mpo`. I have created a new branch with the fixes and am writing the PR now.
