### ISSUE TITLE
Implement local transformations from `quimb`

### ISSUE THREAD

**Issue by mofeing** [bsc-quantic/Tenet.jl#7]
In https://arxiv.org/abs/2002.01935, authors introduced a list of local Tensor Network transformations than simplify their contraction and path finding.
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18

**Comment by jofrevalles** [comment]
All implementations done.

**Comment by mofeing** [comment]
I think there are new transformations implemented in `quimb` so we have to read its source, but this can be done later.

@jofrevalles Could you add information in the docstrings of the transformations?

**Comment by jofrevalles** [comment]
> @jofrevalles Could you add information in the docstrings of the transformations?

Sure! I will do this
