### ISSUE TITLE
Implement `Infinite` boundary conditions for `MatrixProduct` and `ProjectedEntangledPair` 

### ISSUE THREAD

**Issue by jofrevalles** [bsc-quantic/Tenet.jl#77]
### Summary
`MatrixProduct` and `ProjectedEntangledPair` currently have `Open` and `Periodic` boundary conditions. We could enhance these structs by adding the `Infinite` boundary condition, in which a cell-like structure is repeated infinitely many times.

**Comment by mofeing** [comment]
Is infinite a boundary condition? Aren't there infinite open and infinite closed boundary conditions?

**Comment by jofrevalles** [comment]
> Is infinite a boundary condition? Aren't there infinite open and infinite closed boundary conditions?

You are correct that 'infinite' is not traditionally a boundary condition, but rather a property of the system size. When I refer to `Infinite` boundary conditions, I am referring to the case where our tensor network is taken to represent an infinitely repeating structure, like an infinite chain or lattice. This is used commonly in physics systems where there is translational symmetry.

In `iMPS` and `iPEPS` the concept of traditional boundary conditions, such as `Open` or `Periodic`, does not directly apply because of the infinite nature of these systems. However, they inherently possess a sort of periodicity due to the translational symmetry of the infinite system. So, while `Infinite` might not be a boundary condition in the classical sense, I think it holds a specific and significant meaning in the case of Tensor Networks. Also, I have seen a lot of TN libraries use this notation of `Open`, `Periodic` or `Infinite ` boundary conditions.

**Comment by mofeing** [comment]
Okay. Thanks for the explanation!

Then yes, it makes sense to me that `Infinite <: Boundary`.
