### ISSUE TITLE
Implement `tensors` function for `Operator` types

### ISSUE THREAD

**Issue by jofrevalles** [bsc-quantic/Tenet.jl#80]
Currently the `tensors` function is not implemented for `Operator` types. @mofeing argues that it is not easy to implement `tensors` for `Operators` when the input and output sites do not match (e. g. `SpacedMatrixProductOperator`). I think that currently both `MPO` and `PEPO` only support the same input/output sites, so maybe we could just implement that (as #78 intended).

**Comment by mofeing** [comment]
Related code moved to [`Qrochet.jl`](https://github.com/bsc-quantic/Qrochet.jl).
