### ISSUE TITLE
Despecialize `Tensor` struct and methods to decrease compilation time

### ISSUE THREAD

**Issue by mofeing** [bsc-quantic/Tenet.jl#89]
There are some big compilation times when methods specialize on `Tensor`. It might be an issue like what happened to `EinExprs.jl`, where too much specialization was heavily affecting performance.

**Comment by mofeing** [comment]
@jofrevalles I also want to get rid of the `meta` field in `Tensor`. Its semantics when performing binary operations between two `Tensor`s are... weird. And we are not really using it.

There is just one thing blocking the removal of `meta`: hyperindex names. I think I can get alternative solutions for Transformations, but I'm not sure about plotting. Maybe we should use a `TensorNetworkGraphPlot` struct for storing this info when plotting?

**Comment by jofrevalles** [comment]
> There is just one thing blocking the removal of `meta`: hyperindex names. I think I can get alternative solutions for Transformations, but I'm not sure about plotting. Maybe we should use a `TensorNetworkGraphPlot` struct for storing this info when plotting?

So right now we have the `:dual` key in the `meta` `Dict` that has as value the hyperindex `Symbol`. When plotting, we could search in the `tn` for `DeltaArray`s and plot them differently, but I don't know about that. What is your idea on how to represent that?

**Comment by mofeing** [comment]
Yeah, that should be done for sure. I don't think that's a problem.

My main issue is what do we do if we want to plot the labels of the hyperindices.

**Comment by jofrevalles** [comment]
We could define a new `struct` for the labels of the `Tensor`s to handle these cases, but maybe that is too much. Right now, without the `meta` part it would plot a hyperindex `i` with `i1, i2, i3, ...`; maybe this is not so bad after all and we could leave it like this.

**Comment by mofeing** [comment]
Well, maybe we can just get have a mapping from hyperindex name to converted indices and use it for plotting the labels (only the hyperindices). If the user happens to do the conversion before calling `plot` then this will be impossible, but for now is ok.

In the future, I suggest giving more flexibility by letting users use a their own naming scheme in `HyperindsConverter`.
